//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.17 at 01:58:06 PM EDT 
//


package com.ztfd.crestronFusion.api.entities;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for API_AlertRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="API_AlertRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AlertAlways" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AlertOnce" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AlertOperator" type="{http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities}API_Enum_AlertOperator" minOccurs="0"/>
 *         &lt;element name="AlertRuleCriteria" type="{http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities}ArrayOfAPI_AlertRuleCriteria" minOccurs="0"/>
 *         &lt;element name="AlertRuleID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttributeID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LogAttributeInDatabase" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LogAttributeInEventLog" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="NodeID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NodeText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "API_AlertRule", propOrder = {
    "alertAlways",
    "alertOnce",
    "alertOperator",
    "alertRuleCriteria",
    "alertRuleID",
    "attributeID",
    "lastModified",
    "logAttributeInDatabase",
    "logAttributeInEventLog",
    "nodeID",
    "nodeText"
})

@XmlRootElement(name="API_AlertRule")
public class APIAlertRule {

    @XmlElementRef(name = "AlertAlways", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> alertAlways;
    @XmlElementRef(name = "AlertOnce", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> alertOnce;
    @XmlElement(name = "AlertOperator")
    protected APIEnumAlertOperator alertOperator;
    @XmlElementRef(name = "AlertRuleCriteria", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAPIAlertRuleCriteria> alertRuleCriteria;
    @XmlElementRef(name = "AlertRuleID", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> alertRuleID;
    @XmlElementRef(name = "AttributeID", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> attributeID;
    @XmlElementRef(name = "LastModified", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> lastModified;
    @XmlElementRef(name = "LogAttributeInDatabase", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> logAttributeInDatabase;
    @XmlElementRef(name = "LogAttributeInEventLog", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> logAttributeInEventLog;
    @XmlElementRef(name = "NodeID", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nodeID;
    @XmlElementRef(name = "NodeText", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nodeText;

    /**
     * Gets the value of the alertAlways property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getAlertAlways() {
        return alertAlways;
    }

    /**
     * Sets the value of the alertAlways property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setAlertAlways(JAXBElement<Boolean> value) {
        this.alertAlways = value;
    }

    /**
     * Gets the value of the alertOnce property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getAlertOnce() {
        return alertOnce;
    }

    /**
     * Sets the value of the alertOnce property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setAlertOnce(JAXBElement<Boolean> value) {
        this.alertOnce = value;
    }

    /**
     * Gets the value of the alertOperator property.
     * 
     * @return
     *     possible object is
     *     {@link APIEnumAlertOperator }
     *     
     */
    public APIEnumAlertOperator getAlertOperator() {
        return alertOperator;
    }

    /**
     * Sets the value of the alertOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link APIEnumAlertOperator }
     *     
     */
    public void setAlertOperator(APIEnumAlertOperator value) {
        this.alertOperator = value;
    }

    /**
     * Gets the value of the alertRuleCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIAlertRuleCriteria }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAPIAlertRuleCriteria> getAlertRuleCriteria() {
        return alertRuleCriteria;
    }

    /**
     * Sets the value of the alertRuleCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIAlertRuleCriteria }{@code >}
     *     
     */
    public void setAlertRuleCriteria(JAXBElement<ArrayOfAPIAlertRuleCriteria> value) {
        this.alertRuleCriteria = value;
    }

    /**
     * Gets the value of the alertRuleID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAlertRuleID() {
        return alertRuleID;
    }

    /**
     * Sets the value of the alertRuleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAlertRuleID(JAXBElement<String> value) {
        this.alertRuleID = value;
    }

    /**
     * Gets the value of the attributeID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAttributeID() {
        return attributeID;
    }

    /**
     * Sets the value of the attributeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAttributeID(JAXBElement<String> value) {
        this.attributeID = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setLastModified(JAXBElement<XMLGregorianCalendar> value) {
        this.lastModified = value;
    }

    /**
     * Gets the value of the logAttributeInDatabase property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getLogAttributeInDatabase() {
        return logAttributeInDatabase;
    }

    /**
     * Sets the value of the logAttributeInDatabase property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setLogAttributeInDatabase(JAXBElement<Boolean> value) {
        this.logAttributeInDatabase = value;
    }

    /**
     * Gets the value of the logAttributeInEventLog property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getLogAttributeInEventLog() {
        return logAttributeInEventLog;
    }

    /**
     * Sets the value of the logAttributeInEventLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setLogAttributeInEventLog(JAXBElement<Boolean> value) {
        this.logAttributeInEventLog = value;
    }

    /**
     * Gets the value of the nodeID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNodeID() {
        return nodeID;
    }

    /**
     * Sets the value of the nodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNodeID(JAXBElement<String> value) {
        this.nodeID = value;
    }

    /**
     * Gets the value of the nodeText property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNodeText() {
        return nodeText;
    }

    /**
     * Sets the value of the nodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNodeText(JAXBElement<String> value) {
        this.nodeText = value;
    }

}
