//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.17 at 01:58:06 PM EDT 
//


package com.ztfd.crestronFusion.api.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for API_Enum_AlertRuleUnit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="API_Enum_AlertRuleUnit">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Value"/>
 *     &lt;enumeration value="Percent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "API_Enum_AlertRuleUnit")
@XmlEnum
public enum APIEnumAlertRuleUnit {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Value")
    VALUE("Value"),
    @XmlEnumValue("Percent")
    PERCENT("Percent");
    private final String value;

    APIEnumAlertRuleUnit(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static APIEnumAlertRuleUnit fromValue(String v) {
        for (APIEnumAlertRuleUnit c: APIEnumAlertRuleUnit.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
