//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.17 at 01:58:06 PM EDT 
//


package com.ztfd.crestronFusion.api.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for API_Enum_PushNotifyAction.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="API_Enum_PushNotifyAction">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="New"/>
 *     &lt;enumeration value="Change"/>
 *     &lt;enumeration value="Remove"/>
 *     &lt;enumeration value="Refresh"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "API_Enum_PushNotifyAction")
@XmlEnum
public enum APIEnumPushNotifyAction {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("New")
    NEW("New"),
    @XmlEnumValue("Change")
    CHANGE("Change"),
    @XmlEnumValue("Remove")
    REMOVE("Remove"),
    @XmlEnumValue("Refresh")
    REFRESH("Refresh");
    private final String value;

    APIEnumPushNotifyAction(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static APIEnumPushNotifyAction fromValue(String v) {
        for (APIEnumPushNotifyAction c: APIEnumPushNotifyAction.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
