//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 04:31:03 PM EDT 
//


package com.ztfd.crestronFusion.api.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for API_Enum_ObjectType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="API_Enum_ObjectType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Action"/>
 *     &lt;enumeration value="AlertRule"/>
 *     &lt;enumeration value="Appointment"/>
 *     &lt;enumeration value="AssetSignal"/>
 *     &lt;enumeration value="Asset"/>
 *     &lt;enumeration value="AssetType"/>
 *     &lt;enumeration value="AttributeValue"/>
 *     &lt;enumeration value="Attribute"/>
 *     &lt;enumeration value="Contracts"/>
 *     &lt;enumeration value="DistributionGroup"/>
 *     &lt;enumeration value="EmailAlertRule"/>
 *     &lt;enumeration value="EmailTemplate"/>
 *     &lt;enumeration value="HelpRequest"/>
 *     &lt;enumeration value="Node"/>
 *     &lt;enumeration value="People"/>
 *     &lt;enumeration value="Processor"/>
 *     &lt;enumeration value="Role"/>
 *     &lt;enumeration value="Room"/>
 *     &lt;enumeration value="RoomTemplate"/>
 *     &lt;enumeration value="SecurityGroup"/>
 *     &lt;enumeration value="SecurityPolicy"/>
 *     &lt;enumeration value="Server"/>
 *     &lt;enumeration value="Signal"/>
 *     &lt;enumeration value="SymbolSignal"/>
 *     &lt;enumeration value="Symbol"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "API_Enum_ObjectType")
@XmlEnum
public enum APIEnumObjectType {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Action")
    ACTION("Action"),
    @XmlEnumValue("AlertRule")
    ALERT_RULE("AlertRule"),
    @XmlEnumValue("Appointment")
    APPOINTMENT("Appointment"),
    @XmlEnumValue("AssetSignal")
    ASSET_SIGNAL("AssetSignal"),
    @XmlEnumValue("Asset")
    ASSET("Asset"),
    @XmlEnumValue("AssetType")
    ASSET_TYPE("AssetType"),
    @XmlEnumValue("AttributeValue")
    ATTRIBUTE_VALUE("AttributeValue"),
    @XmlEnumValue("Attribute")
    ATTRIBUTE("Attribute"),
    @XmlEnumValue("Contracts")
    CONTRACTS("Contracts"),
    @XmlEnumValue("DistributionGroup")
    DISTRIBUTION_GROUP("DistributionGroup"),
    @XmlEnumValue("EmailAlertRule")
    EMAIL_ALERT_RULE("EmailAlertRule"),
    @XmlEnumValue("EmailTemplate")
    EMAIL_TEMPLATE("EmailTemplate"),
    @XmlEnumValue("HelpRequest")
    HELP_REQUEST("HelpRequest"),
    @XmlEnumValue("Node")
    NODE("Node"),
    @XmlEnumValue("People")
    PEOPLE("People"),
    @XmlEnumValue("Processor")
    PROCESSOR("Processor"),
    @XmlEnumValue("Role")
    ROLE("Role"),
    @XmlEnumValue("Room")
    ROOM("Room"),
    @XmlEnumValue("RoomTemplate")
    ROOM_TEMPLATE("RoomTemplate"),
    @XmlEnumValue("SecurityGroup")
    SECURITY_GROUP("SecurityGroup"),
    @XmlEnumValue("SecurityPolicy")
    SECURITY_POLICY("SecurityPolicy"),
    @XmlEnumValue("Server")
    SERVER("Server"),
    @XmlEnumValue("Signal")
    SIGNAL("Signal"),
    @XmlEnumValue("SymbolSignal")
    SYMBOL_SIGNAL("SymbolSignal"),
    @XmlEnumValue("Symbol")
    SYMBOL("Symbol");
    private final String value;

    APIEnumObjectType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static APIEnumObjectType fromValue(String v) {
        for (APIEnumObjectType c: APIEnumObjectType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
