//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.17 at 01:58:06 PM EDT 
//


package com.ztfd.crestronFusion.api.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for API_Enum_AssetStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="API_Enum_AssetStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Ok"/>
 *     &lt;enumeration value="ServiceDue"/>
 *     &lt;enumeration value="MaintenanceContractExpired"/>
 *     &lt;enumeration value="EconomicLifespanExpired"/>
 *     &lt;enumeration value="AssetMoved"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "API_Enum_AssetStatus")
@XmlEnum
public enum APIEnumAssetStatus {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Ok")
    OK("Ok"),
    @XmlEnumValue("ServiceDue")
    SERVICE_DUE("ServiceDue"),
    @XmlEnumValue("MaintenanceContractExpired")
    MAINTENANCE_CONTRACT_EXPIRED("MaintenanceContractExpired"),
    @XmlEnumValue("EconomicLifespanExpired")
    ECONOMIC_LIFESPAN_EXPIRED("EconomicLifespanExpired"),
    @XmlEnumValue("AssetMoved")
    ASSET_MOVED("AssetMoved");
    private final String value;

    APIEnumAssetStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static APIEnumAssetStatus fromValue(String v) {
        for (APIEnumAssetStatus c: APIEnumAssetStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
