//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 04:31:03 PM EDT 
//


package com.ztfd.crestronFusion.api.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for API_Enum_RecurrenceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="API_Enum_RecurrenceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Endless"/>
 *     &lt;enumeration value="EndDate"/>
 *     &lt;enumeration value="EndCount"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "API_Enum_RecurrenceType")
@XmlEnum
public enum APIEnumRecurrenceType {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Endless")
    ENDLESS("Endless"),
    @XmlEnumValue("EndDate")
    END_DATE("EndDate"),
    @XmlEnumValue("EndCount")
    END_COUNT("EndCount");
    private final String value;

    APIEnumRecurrenceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static APIEnumRecurrenceType fromValue(String v) {
        for (APIEnumRecurrenceType c: APIEnumRecurrenceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
