//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.17 at 01:58:06 PM EDT 
//


package com.ztfd.crestronFusion.api.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for API_Enum_AttributeIOMask.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="API_Enum_AttributeIOMask">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Zero"/>
 *     &lt;enumeration value="Write"/>
 *     &lt;enumeration value="Read"/>
 *     &lt;enumeration value="ReadWrite"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "API_Enum_AttributeIOMask")
@XmlEnum
public enum APIEnumAttributeIOMask {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Zero")
    ZERO("Zero"),
    @XmlEnumValue("Write")
    WRITE("Write"),
    @XmlEnumValue("Read")
    READ("Read"),
    @XmlEnumValue("ReadWrite")
    READ_WRITE("ReadWrite");
    private final String value;

    APIEnumAttributeIOMask(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static APIEnumAttributeIOMask fromValue(String v) {
        for (APIEnumAttributeIOMask c: APIEnumAttributeIOMask.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
