//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.17 at 01:58:06 PM EDT 
//


package com.ztfd.crestronFusion.api.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for API_Enum_MeetingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="API_Enum_MeetingType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="Single"/>
 *     &lt;enumeration value="RecurringMaster"/>
 *     &lt;enumeration value="RecurringInstance"/>
 *     &lt;enumeration value="DeletedInstance"/>
 *     &lt;enumeration value="ModifiedInstance"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "API_Enum_MeetingType")
@XmlEnum
public enum APIEnumMeetingType {

    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("Single")
    SINGLE("Single"),
    @XmlEnumValue("RecurringMaster")
    RECURRING_MASTER("RecurringMaster"),
    @XmlEnumValue("RecurringInstance")
    RECURRING_INSTANCE("RecurringInstance"),
    @XmlEnumValue("DeletedInstance")
    DELETED_INSTANCE("DeletedInstance"),
    @XmlEnumValue("ModifiedInstance")
    MODIFIED_INSTANCE("ModifiedInstance");
    private final String value;

    APIEnumMeetingType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static APIEnumMeetingType fromValue(String v) {
        for (APIEnumMeetingType c: APIEnumMeetingType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
