//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.17 at 01:58:06 PM EDT 
//


package com.ztfd.crestronFusion.api.entities;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for API_Result complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="API_Result">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="API_Actions" type="{http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities}ArrayOfAPI_Action" minOccurs="0"/>
 *         &lt;element name="API_Appointments" type="{http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities}ArrayOfAPI_Appointment" minOccurs="0"/>
 *         &lt;element name="API_Assets" type="{http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities}ArrayOfAPI_Asset" minOccurs="0"/>
 *         &lt;element name="API_Attributes" type="{http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities}ArrayOfAPI_Attribute" minOccurs="0"/>
 *         &lt;element name="API_Nodes" type="{http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities}ArrayOfAPI_Node" minOccurs="0"/>
 *         &lt;element name="API_Rooms" type="{http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities}ArrayOfAPI_Room" minOccurs="0"/>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PageNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StackTrace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalRecords" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "API_Result", propOrder = {
    "apiActions",
    "apiAppointments",
    "apiAssets",
    "apiAttributes",
    "apiNodes",
    "apiRooms",
    "message",
    "pageNumber",
    "source",
    "stackTrace",
    "status",
    "totalRecords"
})

@XmlRootElement(name="API_Result")
public class APIResult {

    @XmlElementRef(name = "API_Actions", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAPIAction> apiActions;
    @XmlElementRef(name = "API_Appointments", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAPIAppointment> apiAppointments;
    @XmlElementRef(name = "API_Assets", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAPIAsset> apiAssets;
    @XmlElementRef(name = "API_Attributes", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAPIAttribute> apiAttributes;
    @XmlElementRef(name = "API_Nodes", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAPINode> apiNodes;
    @XmlElementRef(name = "API_Rooms", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAPIRoom> apiRooms;
    @XmlElementRef(name = "Message", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> message;
    @XmlElement(name = "PageNumber")
    protected Integer pageNumber;
    @XmlElementRef(name = "Source", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> source;
    @XmlElementRef(name = "StackTrace", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> stackTrace;
    @XmlElementRef(name = "Status", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> status;
    @XmlElement(name = "TotalRecords")
    protected Integer totalRecords;

    /**
     * Gets the value of the apiActions property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIAction }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAPIAction> getAPIActions() {
        return apiActions;
    }

    /**
     * Sets the value of the apiActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIAction }{@code >}
     *     
     */
    public void setAPIActions(JAXBElement<ArrayOfAPIAction> value) {
        this.apiActions = value;
    }

    /**
     * Gets the value of the apiAppointments property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIAppointment }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAPIAppointment> getAPIAppointments() {
        return apiAppointments;
    }

    /**
     * Sets the value of the apiAppointments property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIAppointment }{@code >}
     *     
     */
    public void setAPIAppointments(JAXBElement<ArrayOfAPIAppointment> value) {
        this.apiAppointments = value;
    }

    /**
     * Gets the value of the apiAssets property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIAsset }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAPIAsset> getAPIAssets() {
        return apiAssets;
    }

    /**
     * Sets the value of the apiAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIAsset }{@code >}
     *     
     */
    public void setAPIAssets(JAXBElement<ArrayOfAPIAsset> value) {
        this.apiAssets = value;
    }

    /**
     * Gets the value of the apiAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIAttribute }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAPIAttribute> getAPIAttributes() {
        return apiAttributes;
    }

    /**
     * Sets the value of the apiAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIAttribute }{@code >}
     *     
     */
    public void setAPIAttributes(JAXBElement<ArrayOfAPIAttribute> value) {
        this.apiAttributes = value;
    }

    /**
     * Gets the value of the apiNodes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPINode }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAPINode> getAPINodes() {
        return apiNodes;
    }

    /**
     * Sets the value of the apiNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPINode }{@code >}
     *     
     */
    public void setAPINodes(JAXBElement<ArrayOfAPINode> value) {
        this.apiNodes = value;
    }

    /**
     * Gets the value of the apiRooms property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIRoom }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAPIRoom> getAPIRooms() {
        return apiRooms;
    }

    /**
     * Sets the value of the apiRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAPIRoom }{@code >}
     *     
     */
    public void setAPIRooms(JAXBElement<ArrayOfAPIRoom> value) {
        this.apiRooms = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMessage(JAXBElement<String> value) {
        this.message = value;
    }

    /**
     * Gets the value of the pageNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPageNumber() {
        return pageNumber;
    }

    /**
     * Sets the value of the pageNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPageNumber(Integer value) {
        this.pageNumber = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSource(JAXBElement<String> value) {
        this.source = value;
    }

    /**
     * Gets the value of the stackTrace property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStackTrace() {
        return stackTrace;
    }

    /**
     * Sets the value of the stackTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStackTrace(JAXBElement<String> value) {
        this.stackTrace = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStatus(JAXBElement<String> value) {
        this.status = value;
    }

    /**
     * Gets the value of the totalRecords property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalRecords() {
        return totalRecords;
    }

    /**
     * Sets the value of the totalRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalRecords(Integer value) {
        this.totalRecords = value;
    }

}
