//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.17 at 01:58:06 PM EDT 
//


package com.ztfd.crestronFusion.api.entities;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for API_RoleContact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="API_RoleContact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContactID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsRoomViewUser" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SmtpAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UseHtml" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UserID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WebClientUserID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "API_RoleContact", propOrder = {
    "contactID",
    "isRoomViewUser",
    "name",
    "smtpAddress",
    "useHtml",
    "userID",
    "webClientUserID"
})
public class APIRoleContact {

    @XmlElementRef(name = "ContactID", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> contactID;
    @XmlElementRef(name = "IsRoomViewUser", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> isRoomViewUser;
    @XmlElementRef(name = "Name", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> name;
    @XmlElementRef(name = "SmtpAddress", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> smtpAddress;
    @XmlElementRef(name = "UseHtml", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> useHtml;
    @XmlElementRef(name = "UserID", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> userID;
    @XmlElementRef(name = "WebClientUserID", namespace = "http://schemas.datacontract.org/2004/07/Crestron.Fusion.API.Entities", type = JAXBElement.class, required = false)
    protected JAXBElement<String> webClientUserID;

    /**
     * Gets the value of the contactID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getContactID() {
        return contactID;
    }

    /**
     * Sets the value of the contactID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setContactID(JAXBElement<String> value) {
        this.contactID = value;
    }

    /**
     * Gets the value of the isRoomViewUser property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getIsRoomViewUser() {
        return isRoomViewUser;
    }

    /**
     * Sets the value of the isRoomViewUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setIsRoomViewUser(JAXBElement<Boolean> value) {
        this.isRoomViewUser = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setName(JAXBElement<String> value) {
        this.name = value;
    }

    /**
     * Gets the value of the smtpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSmtpAddress() {
        return smtpAddress;
    }

    /**
     * Sets the value of the smtpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSmtpAddress(JAXBElement<String> value) {
        this.smtpAddress = value;
    }

    /**
     * Gets the value of the useHtml property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getUseHtml() {
        return useHtml;
    }

    /**
     * Sets the value of the useHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setUseHtml(JAXBElement<Boolean> value) {
        this.useHtml = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUserID(JAXBElement<String> value) {
        this.userID = value;
    }

    /**
     * Gets the value of the webClientUserID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWebClientUserID() {
        return webClientUserID;
    }

    /**
     * Sets the value of the webClientUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWebClientUserID(JAXBElement<String> value) {
        this.webClientUserID = value;
    }

}
